-- MySQL Script generated by MySQL Workbench
-- Tue Dec 29 00:43:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quiz_angular
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz_angular
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz_angular` DEFAULT CHARACTER SET utf8 ;
USE `quiz_angular` ;

-- -----------------------------------------------------
-- Table `quiz_angular`.`chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_angular`.`chapter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_angular`.`ask`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_angular`.`ask` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(200) NOT NULL,
  `answer` VARCHAR(200) NULL,
  `type` VARCHAR(45) NOT NULL,
  `fk_id_chapter` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_chapter_idx` (`fk_id_chapter` ASC) VISIBLE,
  CONSTRAINT `fk_id_chapter`
    FOREIGN KEY (`fk_id_chapter`)
    REFERENCES `quiz_angular`.`chapter` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_angular`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_angular`.`answer` (
  `id` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `checked` TINYINT NOT NULL,
  `fk_id_ask` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_ask_idx` (`fk_id_ask` ASC) VISIBLE,
  CONSTRAINT `fk_id_ask`
    FOREIGN KEY (`fk_id_ask`)
    REFERENCES `quiz_angular`.`ask` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
